sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 147258sb
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5tPQagT47yVx8fo5pFUA
    access-key-secret: Bz7eW4Fkzh9hsuQzwzgiWPWDUOCspN
    bucket-name: webto-de